version: '2'
services:
    kollex-app:
        container_name: 'kollex-app'
        image: 'node:10'
        command: npm run serve
        working_dir: /opt/app/kollex-app
        volumes:
            - .:/opt/app/kollex-app
        stdin_open: true
        tty: true
        environment:
            DEV_ENV: develop
        ports:
            - '3000:3000'
            - '8080:8080'
    nginx:
        image: 'nginx:latest'
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
